-- Tạo cơ sở dữ liệu
CREATE DATABASE QLKS;

-- Sử dụng cơ sở dữ liệu vừa tạo
USE QLKS;

-- Tạo bảng CUSTOMER
CREATE TABLE CUSTOMER
(
    CUS_ID CHAR(20) CONSTRAINT PK_CUS PRIMARY KEY,
    FULL_NAME NVARCHAR(MAX),
    BIRTHDAY SMALLDATETIME,
    SEX NVARCHAR(4),
    CUS_IDENTITY TINYINT,
    PHONE CHAR(11),
    CAREER NVARCHAR(MAX),
    NATIONALITY NVARCHAR(MAX)
);

-- Tạo bảng STAFF
CREATE TABLE STAFF
(
    STAFF_ID CHAR(20) CONSTRAINT PK_STAFF PRIMARY KEY,
    FULL_NAME NVARCHAR(MAX),
    BIRTHDAY SMALLDATETIME,
    SEX NVARCHAR(4),
    STAFF_IDENTITY TINYINT,
    PHONE CHAR(11),
    STAFF_ADDRESS NVARCHAR(MAX),
    SALARY MONEY,
    POSITION NVARCHAR(MAX)
);

-- Thiết lập định dạng ngày
SET DATEFORMAT DMY;

-- Chèn một bản ghi vào bảng STAFF

-- Tạo bảng HOTELSERVICE
CREATE TABLE HOTELSERVICE
(
    SER_ID CHAR(20) CONSTRAINT PK_SER PRIMARY KEY,
    STAFF_ID CHAR(20),
    FULL_NAME NVARCHAR(50),
    PRICE MONEY,
    FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID)
);

-- Tạo bảng ROOM
CREATE TABLE ROOM
(
    RO_ID CHAR(20) CONSTRAINT PK_RO PRIMARY KEY,
    RO_TYPE NVARCHAR(50),
    PRICE_HOUR MONEY,
    PRICE_DAY MONEY,
    PRICE_NIGHT MONEY
);

-- Tạo bảng BILL
CREATE TABLE BILL
(
    BILL_ID INT IDENTITY(1,1) CONSTRAINT PK_BI PRIMARY KEY,
    RO_ID CHAR(20),
	STT INT,
    CUS_ID CHAR(20) NULL,
    SER_ID CHAR(20) NULL,
    BILL_DATE SMALLDATETIME,
    PRICE MONEY,
    CONSTRAINT BILL_CUS_ID_FK FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER(CUS_ID),
    CONSTRAINT BILL_RO_ID_FK FOREIGN KEY (RO_ID) REFERENCES ROOM(RO_ID),
    CONSTRAINT BILL_SER_ID_FK FOREIGN KEY (SER_ID) REFERENCES HOTELSERVICE(SER_ID)
);

-- Tạo bảng BOOKROOM
CREATE TABLE BOOKROOM
(
    B_ID INT IDENTITY(1,1) CONSTRAINT PK_B PRIMARY KEY,
    CUS_ID CHAR(20) NULL,
    CUS_NAME NVARCHAR(MAX),
	CUS_CO INT,
	CUS_TYPE NVARCHAR (MAX),
    RO_ID CHAR(20),
    SER_ID CHAR(20) NULL,
    DAY_ARRIVAL SMALLDATETIME,
    DAY_LEFT SMALLDATETIME,
    DAY_BOOK SMALLDATETIME,
    FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER(CUS_ID),
    FOREIGN KEY (RO_ID) REFERENCES ROOM(RO_ID),
    FOREIGN KEY (SER_ID) REFERENCES HOTELSERVICE(SER_ID)
);

-- Tạo bảng USERSROLE
CREATE TABLE USERSROLE
(
    ROLE_ID INT PRIMARY KEY,
    DISPLAYNAME NVARCHAR(MAX)
);


-- Tạo bảng USERS
CREATE TABLE USERS
(
    US_ID CHAR(20) CONSTRAINT PK_US PRIMARY KEY,
    US_USERNAME VARCHAR(MAX),
    US_PASSWORD VARCHAR(MAX),
    STAFF_ID CHAR(20),
    DISPLAYNAME NVARCHAR(MAX),
    ROLE_ID INT,
    SOURCES VARCHAR(MAX),
    FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID),
    FOREIGN KEY (ROLE_ID) REFERENCES USERSROLE(ROLE_ID)
);
